---
development:
  dialect: mysql
  database: bookings
  user: root
  password: 0811
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:0811@tcp(127.0.0.1:3306)/bookings"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:0811@tcp(127.0.0.1:3306)/bookings"}}
